### ISSUE TITLE
Ermöglichen nach allen Wahlkreisen im jeweiligen Bundesland zu suchen

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#25]
die neue Tabelle ist in der Produktionsumgebung angelegt.

Abfrage per API wie folgt:

    $optionValues = civicrm_api4('OptionValue', 'get', [
      'select' => [
        'name', 
        'value',
      ],
      'where' => [
        ['option_group_id', '=', 112],
      ],
      'limit' => 25,
    ]);

Wobei: name=Wahlkreisnr., value=Name des Bundeslands

**Comment by grandeljay** [comment]
@Detsieber ist es möglich dass Feld für das Bundesland von `value` auf irgend etwas anderes zu benennen? z. B. `state`? Dann kann ich die Abfrage nämlich anpassen und habe direkt PLZ, Wahlkreis und Bundesland in einer Abfrage:

```php
$optionValues = civicrm_api4('OptionValue', 'get', [
  'groupBy' => [
    'label',
  ],
  'where' => [
    ['OR', [['option_group_id', '=', 112], ['option_group_id', '=', 110]]], 
    ['label', '=', 1], // debug, remove this
  ],
  'limit' => 100, // debug, remove this
  'checkPermissions' => FALSE,
]);
```

**Comment by Detsieber** [comment]
Das ist leider nicht möglich!

Wir müssen für diesen Featurewunsch eine andere Lösung finden.

**Comment by grandeljay** [comment]
Standardmäßig sollen alle Bundesländer durchsucht werden.
