### ISSUE TITLE
Abgeordnetenwatch Profil bei den Kandidaten anzeigen/verlinken

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#26]
i. e. Link to https://www.abgeordnetenwatch.de/profile/annalena-baerbock

**Comment by grandeljay** [comment]
@Detsieber wäre es möglich diese CSV Datei ins CRM zu importieren und den entsprechenden Kandidaten (soweit vorhanden) zuzuordnen?

[profiles.csv](https://github.com/CO2-Abgabe/massnahmenpakete/files/6948976/profiles.csv)

Falls nicht könnte ich auch etwas Programmieren aber wenn es nicht zu viel Aufwand wäre, fände ich es eleganter das übers CRM zu lösen.

**Comment by Detsieber** [comment]
Grundsätzlich wäre es möglich, die Daten ins CiviCRM zu importieren.
Dazu können wir die standardmäßige Importfunktionalität von CiviCRM verwenden.
Den Link würde ich am einfachsten in ein neues Custom Field übernehmen.

Um die Kontakte beim Importieren zuzuordnen, können wir als Schlüsselfelder den Vor- und Nachnamen verwenden - das wird in den meisten Fällen funktionieren. -> es gibt allerdings eine Reihe von Kandidat*innen, deren Vor- und Nachname mehrfach vorkommen, wobei die Dubletten nicht unbedingt Kandidat*innen sein müssen (Beispiele: Christian Schmidt, Stefan Schmidt, ...)

Diese Fälle wird CiviCRM beim Importieren als "Dubletten-Fehler" loggen. Die entsprechende Fehlerdatei müsste dann einfach manuell nachgearbeitet werden (ich gehe davon aus, dass das nicht mehr als 10-20 Fälle betreffen wird, die locker in weniger als einer Stunde abgearbeit werden können.

Vorarbeiten bei der csv-Datei: 
- Aus den Links müssten die Vor- und Nachnamen extrahiert werden.

Vorarbeiten im CiviCRM: 
- Anlegen Custom Field "Link bei Abgeordnetenwatch"
- Anlegen einer Dublettenregel "Vor- und Nachname"

Lasst uns morgen beim Jour Fixe über das Vorgehen sprechen.

**Comment by grandeljay** [comment]
Alles klar, ich habe nun 2 Formeln hinzugefügt damit die Namen anhand der URL extrahiert werden. Bei Namen die scheinbar öfters vorkommen ist eine Zahl noch in der URL angehangen, die sich dann auch auf den Namen auswirkt ist das schlimm?

![image](https://user-images.githubusercontent.com/45571053/129777396-fd1b6c72-797a-4d09-ae16-22d4a4a6432c.png)

Ansonsten sind hier die Dateien zum weiterverarbeiten:
[profiles.csv](https://github.com/CO2-Abgabe/massnahmenpakete/files/7002076/profiles.csv)
[profiles.ods](https://github.com/CO2-Abgabe/massnahmenpakete/files/7002077/profiles.ods)

**Comment by mariav0** [comment]
Danke, Jay!
Ich hab die Zahlen im Namen via Formel noch vorher entfernt und alle Daten migriert. Die Kontakte sind mit dem Tag "Abgeordnetenwatch" versehen.
Ein paar Kontakte konnte CiviCRM aufgrund gleichen Namens nicht zuordnen (siehe Anhang).
Wie soll hier weiter vorgegangen werden? Soll ich die übrig gebliebenen Links noch manuell den richtigen Kontakten (sofern möglich) zuordnen?

[Import_Errors-Abgeordnetenwatch.csv](https://github.com/CO2-Abgabe/massnahmenpakete/files/7008209/Import_Errors-Abgeordnetenwatch.csv)

**Comment by grandeljay** [comment]
@CO2-Abgabe/civiservice ich arbeite momentan an der Umsetzung, und stelle fest, dass es einfacher wäre, wenn der Link zu abgeordnetenwatch auch eine `Website` Entität (wie bei den (Sozielen Netzwerken) wäre. 

Ist es für euch aufwendig das anzupassen? Falls schon ist es auch kein prob, dachte ich frage nur mal vorher.

**Comment by Detsieber** [comment]
Man könnte das umstellen. Dazu müssten wir die Daten exportieren und nochmal neu importieren. Aufwand alles in allem ca. 0,5 bis maximal 1h.

**Comment by grandeljay** [comment]
Alles klar, danke. Dann lass lieber alles wie es ist.
