### ISSUE TITLE
Delete MP20

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#34]
Since it's showing in an Email template and not used.
![image](https://user-images.githubusercontent.com/45571053/127530544-1ad66bf6-4453-4ff5-be8b-8a45d64d01bb.png)

**Comment by Detsieber** [comment]
The email template was already fixed by someone else.

Now, I also deactivated (not: deleted) the custom fields for MP20, since they are not used. 
Therefore, MP20 related fields are no longer available.

Issue is solved and ticket can be closed.
