### ISSUE TITLE
Allow setting featured candidates

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#38]
Candidates are currently listed alphabetically. It would be more interesting to manually decide which candidates should appear first.

I think there are two ways of approaching this:
1. Tag candidates as featured
2. Add a numeric custom order field to override the default sorting order (i. e. 1 is first, etc)

![image](https://user-images.githubusercontent.com/45571053/128386285-b07a4c47-50b3-4014-9eae-fb53b96e0e9c.png)

Potential custom order would be:
1. Laschet
2. Baerbock
3. Scholz
4. Wissler
5. Lindner
6. Bareiss
7. Jung
8. Winter
9. Hoffmann
10. Schwarzelühr-Sutter

**Comment by grandeljay** [comment]
@Detsieber ich habe gedacht die 2. Option wäre vielleicht sinnvoller, was denkst du?

**Comment by Detsieber** [comment]
Ich habe den use case noch nicht verstanden: Geht es darum, dass a) der Webseitenbesucher selber sortieren kann, oder soll b) eine generelle Reihenfolge der Kandidaten vorgegeben werden?

Im Falle von b): Es müsste dann eine übergeordnete Reihenfolge eingeführt werden, wie die Kandidaten aufgelistet werden. Das ist erst mal eine Aufgabe für Jörg und sein Content-Team... Ist mir aber sehr unklar, welche Reihenfolge da passen würde.

Ggf. könnte man nur bei gefilterten Ausgaben eine Rangfolge nach Pateien vorgeben. Oder die bekannten Kandidaten kommen ganz nach oben.

**Comment by grandeljay** [comment]
Es geht darum dass man beim Erst-Aufruf der Seite die ganzen interessanten Politiker zuerst aufgelsitet sehen sollte.

Ich dachte wenn es ein zusätzliches "Order/Weight" Feld o. ä. geben würde können wir die Alphabetische Reihenfolge beibehalten und bei Kandidaten die einen Wert gesetzt haben mit Priorität anzeigen.

So kann man im CRM nach Bedarf die Reihenfolge der Auflistung immer wieder nach Wunsch ändern

**Comment by Detsieber** [comment]
Ich habe ein neues Custom Field "Super-Sort" beim Abstimmungsverhalten angelegt.
Dort können featured candidates mit einer Gewichtung eingetragen werden, z.B.:
-100 = sehr weit ober
-99   = gleich danach
-10
-8
-6     = weitere featured candidates.
0 oder leer = keine besondere Sortierung.

Die Anzeige in "Bewertungen vergleichen" sollte demnach als erstes Sortierkriterium das Feld "Super Sort" verwenden, als zweites (wie bisher) Sortierkriterium den Sortiernamen.

Die Spitzenkandidat*innen der Parteien habe ich schon mal (soweit sie in #waehlbar2021 eingetragen sind) mit einer vorläufigen Sortiergewichtung versehen.

**Comment by grandeljay** [comment]
Scheinbar werden `NULL` Einträge priorisiert, wäre es möglich immer bzw standardmäßig `0` für das Feld zu verwenden?

**Comment by grandeljay** [comment]
Mit dem Zusatz
```
  'orderBy' => [
    'Abstimmungsverhalten.Super_Sort' => 'ASC', 
    'sort_name' => 'ASC',
  ],
 ```
 
 Erscheinen `NULL`Einträge zuerst und wenn ich die Sortierung auf `DESC` ändere, erscheinen `0` Einträge zuerst

**Comment by Detsieber** [comment]
Ich sehe, das ist bereits erledigt: Das Feld hat als Standard-Eintrag "0", und es sind auch alle Einträge besetzt:
 ```
mysql> select distinct(super_sort_114) from civicrm_value_abstimmungsve_7;
+----------------+
| super_sort_114 |
+----------------+
|           -100 |
|            -90 |
|            -89 |
|            -80 |
|            -60 |
|            -50 |
|            -10 |
|             -9 |
|              0 |
+----------------+
9 rows in set (0,00 sec)
```
Es gibt auch eine Liste von featured Kandidat*innen:

```
mysql> select a.entity_id, c.sort_name from civicrm_value_abstimmungsve_7 as a, civicrm_contact as c where a.super_sort_114
+-----------+-----------------------+
| entity_id | sort_name             |
+-----------+-----------------------+
|      9959 | Laschet, Armin        |
|        23 | Baerbock, Annalena    |
|      2157 | Habeck, Robert, Dr.   |
|      2353 | Scholz, Olaf          |
|       593 | Lindner, Christian    |
|      5674 | Dobrindt, Alexander   |
|       667 | Wissler, Janine       |
|       528 | Bartsch, Dietmar, Dr. |
+-----------+-----------------------+
8 rows in set (0,00 sec)
```
Die Sortierung funktioniert allerdings noch nicht... Ich nehme an, der Code ist noch nicht im Produktivsystem eingespielt?

**Comment by grandeljay** [comment]
Sehr merkwürdig, gestern Mittag Hatte ich noch diverse `NULL` Einträge, daher hatte ich noch nicht hoch geladen. Die Sortierung war dementsprechend auch wirr. Ich werde die Änderungen heute Abend mal hoch laden.

**Comment by grandeljay** [comment]
Ich habe es noch einmal geprüft und bekomme noch sehr viele `NULL` Werte. Wäre gut wenn das noch geändert werden kann, damit ich das Feature heute hochladen kann:

```php
$contacts = civicrm_api4('Contact', 'get', [
  'select' => [
    'COUNT(*) AS count',
  ],
  'where' => [
    ['Abstimmungsverhalten.Super_Sort', 'IS NULL'],
  ],
  'checkPermissions' => FALSE,
]);
```

Ergebnis:
```php
    (1) [
      {
        "count": 5645
      }
    ]
```

**Comment by Detsieber** [comment]
Das ist merkwürdig:
```
mysql> select distinct (super_sort_114 ) from civicrm_value_abstimmungsve_7;
+----------------+
| super_sort_114 |
+----------------+
|           -100 |
|            -90 |
|            -89 |
|            -80 |
|            -60 |
|            -50 |
|            -10 |
|             -9 |
|              0 |
+----------------+
9 rows in set (0,00 sec)
```
Demnach gibt es keine NULL-Werte in der Tabelle.

Die Lösung dürfte hier liegen:
```
mysql> select count(*) from civicrm_value_abstimmungsve_7;
+----------+
| count(*) |
+----------+
|     2121 |
+----------+
1 row in set (0,00 sec)
```
Es gibt 2121 Einträge in der Tabelle mit den Abstimmungen.
```
mysql> select count(*) from civicrm_contact;
+----------+
| count(*) |
+----------+
|     8180 |
+----------+
1 row in set (0,00 sec)
```
Und insgesamt 8180 Kontakte. Davon haben tatsächlich 8180-212=6059 keinen Eintrag, also NULL im Feld supersort.
-> Aber das sind alles keine Kandidat*innen!
Insofern sollte die Sortierung eigentlich passen. Oder wir haben noch einen anderen Fehler.

**Comment by grandeljay** [comment]
Auf meiner Entwicklungsumgebung war die Sortierung nicht wie erwartet, obwohl ich mir ein aktuellen DB Backup vom Live System gezogen habe. Ich vermute dass tatsächlich einige Kandidaten noch NULL Werte im Super Sort field haben. Ich kann leider erst heute Abend ein konkreten Beispiel nennen.

**Comment by Detsieber** [comment]
Hallo Jay, nochmal ganz klar:
```
mysql> select count(*) from civicrm_value_abstimmungsve_7 where super_sort_114 is NULL;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0,00 sec)
```
Es gibt wirklich keine Kandidaten mit NULL  im Super Sort field!

Entweder der Datenbank-Stand auf der Development-Umgebung ist nicht aktuell, oder es gibt einen anderen Fehler.
Die Ausgabe 
```
(1) [
      {
        "count": 5645
      }
    ]
```
deutet darauf hin, dass der Datenbankstand bei dir doch nicht aktuell ist.

**Comment by grandeljay** [comment]
Hallo Detlev,

ich habe mir eben ein neuen Datenbankbackup gezogen, habe jedoch das gleiche Ergebnis wie zuvor. Die Auflistung sieht wie folgt aus:

![image](https://user-images.githubusercontent.com/45571053/129772820-f73ce749-2310-41ee-ac1c-61234c1d5aac.png)

Hier zum nachvollziehen der code zum ersten Kontakt:
```php
$contacts = civicrm_api4('Contact', 'get', [
  'select' => [
    'display_name', 
    'Abstimmungsverhalten.Super_Sort',
  ],
  'where' => [
    ['id', '=', 10157],
  ],
  'limit' => 25,
  'checkPermissions' => FALSE,
]);
```

Ergebnis:
```php
    (1) [
      {
        "id": 10157,
        "display_name": "Volker Beil",
        "Abstimmungsverhalten.Super_Sort": null
      }
    ]
```

**Comment by Detsieber** [comment]
Hallo Jay, nochmal ganz klar:
```
mysql> select count(*) from civicrm_value_abstimmungsve_7 where super_sort_114 is NULL;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0,00 sec)
```
Es gibt wirklich keine Kandidaten mit NULL  im Super Sort field!

Entweder der Datenbank-Stand auf der Development-Umgebung ist nicht aktuell, oder es gibt einen anderen Fehler.
Die Ausgabe 
```
(1) [
      {
        "count": 5645
      }
    ]
```
deutet darauf hin, dass der Datenbankstand bei dir doch nicht aktuell ist.

**Comment by Detsieber** [comment]
Hallo Jay, ich habe das Problem jetzt nachvollzogen. War in der Tat ein gedanklicher Fehler bei mir:
Das Problem liegt darin, dass die Tabelle "civicrm_value_abstimmungsve_7" nicht für jeden Kontakt einen Datensatz enthält - sondern erst, wenn dort etwas abgespeichert wird. In solchen Fällen gibt die API allerdings den Wert NULL aus - was die Sortierung durcheinanderbringt.

Ich sehe jetzt folgenden - sehr einfach - Lösungsweg: Die Sortierung sollte nicht aufsteigend, sondern absteigend erfolgen.
Damit das funktioniert, habe ich die Werte -100, -90, -80 usw. auf 100, 90, 80, ... geändert. Und die Werte mit "0" auf NULL abgeändert.

Damit sollte dann alles funktionieren!
