### ISSUE TITLE
Staging umgebung aktualisieren

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#48]
Aufgrund der letzten Änderungen scheint die nicht mehr mit dem Plugin kompatibel zu sein, wäre gut wenn die demnächst aktualisiert werden könnte, eilt aber nicht.

```log
Fatal error: Uncaught API_Exception: [0]: Invalid field 'Abstimmungsverhalten.Super_Sort' thrown in [...]/civicrm/civicrm/Civi/Api4/Query/Api4SelectQuery.php on line 320
```

**Comment by Detsieber** [comment]
Hallo Jay,
die staging-Umgebung ist aktualisiert und entspricht dem Stand von 25.8.2021, 6:45

**Comment by grandeljay** [comment]
Vielen Dank!
