### ISSUE TITLE
Nach Bundestagsabgeordneten suchen

### ISSUE THREAD

**Issue by grandeljay** [CO2-Abgabe/massnahmenpakete#52]
Via einem CiviCRM Tag o. ä. soll es die Möglichkeit geben, nach gewählten Bundestagsabgeordneten zu suchen.

@Detsieber wäre gut wenn du mir hierfür bald etwas (Tag, Gruppe, etc) zur Verfügung stellen kannst damit ich die Umsetzungen schon mal vorbereiten kann.

**Comment by Detsieber** [comment]
Hallo Jay,

ich habe ein Tag angelegt mit dem Namen: "Gewählt in den 20. Deutschen 
Bundestag"
(dieser Name wird nur im CiviCRM angezeigt und kann jederzeit geändert 
werden)

Die Tag-ID ist 48.


Kommst du damit klar?

LG
Detlev

Am 08.09.21 um 17:51 schrieb Jay:
